name: Test whl install
on:
  workflow_dispatch: # Allow manual triggers
    inputs:
      python_version:
        description: 'Python version'
        required: false
        default: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: ${{  inputs.python_version  }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install twine wheel
      - name: Build WHL file
        run: |
          version=$(python -c 'import model_compression_toolkit; print(model_compression_toolkit.__version__)')
          now=$(date +'%Y%m%d-%H%M%S')
          echo "nightly_version=$version.$now" >> $GITHUB_ENV
          sed -i "s/attr: model_compression_toolkit.__version__/$version.$now/g" setup.cfg
          sed -i "s/name='model_compression_toolkit'/name='model-compression-toolkit'/g" setup.py
          python setup.py sdist bdist_wheel
      - name: Install WHL file
        run: |
          whl_file=$(find . -iname "*.whl")
          echo $whl_file
          pip install $whl_file
          pip list
          python -c 'import model_compression_toolkit; print(model_compression_toolkit.__version__)'
